import type { Journey } from "@/types/content";

export const commonThreadJourney: Journey = {
  id: "common-thread",
  slug: "common-thread",
  title: "The Common Thread",
  description: "Seven thresholds through the recurring human work of placing life, death, community and cosmos into meaningful relationship—without turning different cultures into one flattened story.",
  durationLabel: "7 thresholds · about 12 minutes",
  closingTitle: "The ancient sites return the work to us.",
  closingText: "Every civilisation places something at its centre. Our task is to build what helps humanity remember, cooperate, heal and become more conscious—and to make those structures beautiful enough that people freely choose to enter.",
  closingPrompt: "What will we build around now—and will it help life flourish beyond us?",
  steps: [
    {
      id: "we-gather",
      title: "We Gather",
      siteId: "gobekli-tepe",
      siteName: "Göbekli Tepe",
      locationLabel: "Upper Mesopotamia · c. 9600–8200 BCE",
      eyebrow: "Threshold 01 · Community",
      voice: "Meaning gathers us.",
      humanInsight: "Before writing, empires or monumental cities, people already invested enormous effort in spaces that made shared symbols and social bonds visible.",
      image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Gobeklitepe_Panorama.jpg",
      imageAlt: "Archaeological photograph of Göbekli Tepe's carved T-shaped pillars at dawn",
      imageLabel: "Archaeological photograph",
      claimIds: ["gobekli-monumental-gathering"],
      reflection: "What brings separate people into a shared world?",
      gestureKind: "gather",
      gestureInstruction: "Bring the four markers into relation. The gesture represents coordinated attention, not a reconstruction of an ancient rite.",
      gestureCompletion: "A shared centre appears only when separate positions begin to relate.",
      culturalBoundary: "Göbekli Tepe is not evidence that every later religion came from one forgotten doctrine. Its enclosures belong first to their own Neolithic place and communities.",
      carryForward: "Gathering creates a shared world. The next threshold asks how a community learns to share time."
    },
    {
      id: "we-watch",
      title: "We Watch",
      siteId: "stonehenge",
      siteName: "Stonehenge",
      locationLabel: "Wiltshire · Neolithic and Bronze Age",
      eyebrow: "Threshold 02 · Time",
      voice: "Time is sacred.",
      humanInsight: "To watch the sky together is to transform time from an invisible flow into a shared rhythm of return, memory and expectation.",
      image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Stonehenge_at_Sunrise.jpg",
      imageAlt: "Archaeological photograph of Stonehenge in mist at sunrise",
      imageLabel: "Archaeological photograph",
      claimIds: ["stonehenge-ceremonial-landscape"],
      reflection: "Which rhythms still gather and orient your community?",
      gestureKind: "watch",
      gestureInstruction: "Move the light across the horizon and pause at return. This is a symbolic observation exercise, not an alignment calculator.",
      gestureCompletion: "A recurring horizon can turn passing time into a shared expectation.",
      culturalBoundary: "Stonehenge changed across many generations and sat within a wider ceremonial landscape. It should not be reduced to a single observatory, calendar or timeless Celtic symbol.",
      carryForward: "Watching return makes time inhabitable. The next threshold brings returning light into an enclosed chamber."
    },
    {
      id: "we-invite-light",
      title: "We Invite Light Back",
      siteId: "newgrange",
      siteName: "Newgrange",
      locationLabel: "Brú na Bóinne · Ireland · c. 3200 BCE",
      eyebrow: "Threshold 03 · Renewal",
      voice: "Light returns through stone.",
      humanInsight: "At midwinter, architecture turns a cosmic event into an intimate encounter: a narrow beam travels into darkness and reaches the chamber within.",
      image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/NewgrangeTombEntrance.jpg",
      imageAlt: "The entrance and roof box of Newgrange passage tomb",
      imageLabel: "Archaeological photograph · public domain",
      claimIds: ["newgrange-solstice-light"],
      reflection: "What helps a human being trust that darkness is not the whole story?",
      gestureKind: "invite-light",
      gestureInstruction: "Guide a narrow beam toward the chamber. The geometry is interpretive; the documented midwinter illumination is the evidence-led centre.",
      gestureCompletion: "Architecture can make a distant celestial return feel intimate and interior.",
      culturalBoundary: "Newgrange is an Irish passage tomb with a long, changing history. Its solstice illumination does not prove a universal resurrection doctrine shared by all monument builders.",
      carryForward: "Light can be invited back. The next threshold asks how a society makes order endure far beyond one human life."
    },
    {
      id: "we-endure",
      title: "We Build for Eternity",
      siteId: "giza",
      siteName: "Giza",
      locationLabel: "Old Kingdom Egypt · c. 26th century BCE",
      eyebrow: "Threshold 04 · Eternity",
      voice: "Make order endure.",
      humanInsight: "Giza joined landscape, labour, kingship, cardinal orientation and funerary architecture in a project designed to outlast an individual life.",
      image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Giza_Pyramids_Panorama.jpg",
      imageAlt: "Archaeological photograph of the Giza pyramid complex in golden light",
      imageLabel: "Archaeological photograph",
      claimIds: ["giza-khufu-tomb", "giza-cardinal-alignment", "giza-royal-complex"],
      reflection: "What deserves to be preserved beyond one lifetime?",
      gestureKind: "endure",
      gestureInstruction: "Activate stone, water, labour and orientation. The symbolic system resists the fantasy that one secret technique explains the monument.",
      gestureCompletion: "Endurance emerges from coordinated material, social, spatial and symbolic systems.",
      culturalBoundary: "Giza belongs to Old Kingdom Egyptian kingship, burial practice and cosmic order. Its precision is not evidence for aliens, a global pyramid cult or one hidden modern science.",
      carryForward: "Some monuments rise toward endurance. The next threshold turns downward, toward mortality and the world beneath."
    },
    {
      id: "we-descend",
      title: "We Descend",
      siteId: "hal-saflieni",
      siteName: "Ħal Saflieni",
      locationLabel: "Malta · c. 4000–2500 BCE",
      eyebrow: "Threshold 05 · Death",
      voice: "Descend inward.",
      humanInsight: "Not every sacred centre reaches upward. Some lead below the surface, using darkness, enclosure and carved chambers to hold the dead and alter the attention of the living.",
      image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Hal_Saflieni_Hypogeum_%E2%80%93_Middle_Level_%E2%80%93_The_Central_Chamber.jpg",
      imageAlt: "Archaeological photograph of the Ħal Saflieni Hypogeum's carved underground chambers",
      imageLabel: "Archaeological photograph",
      claimIds: ["hal-saflieni-subterranean-cemetery"],
      reflection: "What can only be encountered when we stop fleeing depth and mortality?",
      gestureKind: "descend",
      gestureInstruction: "Move through three symbolic depths. The exercise evokes changing attention; it does not reproduce the original route or ritual sequence.",
      gestureCompletion: "Descent changes the scale of attention: from open world, to chamber, to the fact of mortality.",
      culturalBoundary: "The Hypogeum is a specific Maltese subterranean cemetery and ritual complex. Acoustic or mystical interpretations must not outrun the archaeological record.",
      carryForward: "Descent gathers the dead and living into one depth. The next threshold expands sacred order into water, city and cultivated land."
    },
    {
      id: "we-shape-a-world",
      title: "We Shape a Living World",
      siteId: "angkor",
      siteName: "Angkor",
      locationLabel: "Khmer Empire · 9th–15th centuries",
      eyebrow: "Threshold 06 · Civilisation",
      voice: "Let the cosmos flow.",
      humanInsight: "At Angkor, temples were embedded in cities, reservoirs, canals, routes, farms and living communities. The sacred was not outside practical life; it helped organise a world.",
      image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Angkor_Wat_with_its_reflection_(cropped).jpg",
      imageAlt: "Archaeological photograph of Angkor Wat reflected in water at sunrise",
      imageLabel: "Archaeological photograph",
      claimIds: ["angkor-hydraulic-cosmos"],
      reflection: "What would it mean for our infrastructure to express care, balance and belonging?",
      gestureKind: "flow",
      gestureInstruction: "Connect water, settlement, cultivation and temple. The network is a conceptual relationship map, not a hydraulic simulation of Angkor.",
      gestureCompletion: "A living centre depends on flows between practical infrastructure, political power, ecology and sacred meaning.",
      culturalBoundary: "Angkor was a changing Khmer urban region, not one frozen temple-city. Its water systems should not be romanticised as perfectly harmonious or explained by cosmology alone.",
      carryForward: "A sacred world can be distributed through an inhabited landscape. The final threshold makes the teaching itself a path."
    },
    {
      id: "we-walk",
      title: "We Walk the Teaching",
      siteId: "borobudur",
      siteName: "Borobudur",
      locationLabel: "Central Java · 8th–9th centuries",
      eyebrow: "Threshold 07 · Transformation",
      voice: "The path changes the traveller.",
      humanInsight: "Borobudur does not only depict a cosmology. Its terraces invite movement through it, turning ascent, circling, relief and changing form into a physical pedagogy.",
      image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Borobudur_Sunrise.jpg",
      imageAlt: "Archaeological photograph of Borobudur's stupas above a misty valley",
      imageLabel: "Archaeological photograph",
      claimIds: ["borobudur-walking-cosmology"],
      reflection: "Which truths can be understood only by practising and moving through them?",
      gestureKind: "walk",
      gestureInstruction: "Advance through three symbolic terraces. The sequence evokes embodied learning without claiming to reproduce a historical pilgrim's complete experience.",
      gestureCompletion: "A teaching becomes different when the body must circle, climb, pause and continue.",
      culturalBoundary: "Borobudur is a Javanese Buddhist monument with specific narratives, practices and historical contexts. It is not merely a generic mandala or universal self-help metaphor.",
      carryForward: "The seven sites do not resolve into one doctrine. They return seven different ways of giving form to what a society holds sacred."
    }
  ]
};
