import type { Journey } from "@/types/content";

export const commonThreadJourney: Journey = {
  id: "common-thread",
  slug: "common-thread",
  title: "The Common Thread",
  description: "Seven thresholds through the recurring human work of placing life, death, community and cosmos into meaningful relationship—without turning different cultures into one flattened story.",
  durationLabel: "7 thresholds · about 12 minutes",
  closingTitle: "The ancient sites return the work to us.",
  closingText: "Every civilisation places something at its centre. Our task is to build what helps humanity remember, cooperate, heal and become more conscious—and to make those structures beautiful enough that people freely choose to enter.",
  closingPrompt: "What will we build around now—and will it help life flourish beyond us?",
  steps: [
    {
      id: "we-gather",
      title: "We Gather",
      siteId: "gobekli-tepe",
      siteName: "Göbekli Tepe",
      locationLabel: "Upper Mesopotamia · c. 9600–8200 BCE",
      eyebrow: "Threshold 01 · Community",
      voice: "Meaning gathers us.",
      humanInsight: "Before writing, empires or monumental cities, people already invested enormous effort in spaces that made shared symbols and social bonds visible.",
      image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Gobeklitepe_Panorama.jpg",
      imageAlt: "Archaeological photograph of Göbekli Tepe's carved T-shaped pillars at dawn",
      imageLabel: "Archaeological photograph",
      claimIds: ["gobekli-monumental-gathering"],
      reflection: "What brings separate people into a shared world?"
    },
    {
      id: "we-watch",
      title: "We Watch",
      siteId: "stonehenge",
      siteName: "Stonehenge",
      locationLabel: "Wiltshire · Neolithic and Bronze Age",
      eyebrow: "Threshold 02 · Time",
      voice: "Time is sacred.",
      humanInsight: "To watch the sky together is to transform time from an invisible flow into a shared rhythm of return, memory and expectation.",
      image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Stonehenge_at_Sunrise.jpg",
      imageAlt: "Archaeological photograph of Stonehenge in mist at sunrise",
      imageLabel: "Archaeological photograph",
      claimIds: ["stonehenge-ceremonial-landscape"],
      reflection: "Which rhythms still gather and orient your community?"
    },
    {
      id: "we-invite-light",
      title: "We Invite Light Back",
      siteId: "newgrange",
      siteName: "Newgrange",
      locationLabel: "Brú na Bóinne · Ireland · c. 3200 BCE",
      eyebrow: "Threshold 03 · Renewal",
      voice: "Light returns through stone.",
      humanInsight: "At midwinter, architecture turns a cosmic event into an intimate encounter: a narrow beam travels into darkness and reaches the chamber within.",
      image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/NewgrangeTombEntrance.jpg",
      imageAlt: "The entrance and roof box of Newgrange passage tomb",
      imageLabel: "Archaeological photograph · public domain",
      claimIds: ["newgrange-solstice-light"],
      reflection: "What helps a human being trust that darkness is not the whole story?"
    },
    {
      id: "we-endure",
      title: "We Build for Eternity",
      siteId: "giza",
      siteName: "Giza",
      locationLabel: "Old Kingdom Egypt · c. 26th century BCE",
      eyebrow: "Threshold 04 · Eternity",
      voice: "Make order endure.",
      humanInsight: "Giza joined landscape, labour, kingship, cardinal orientation and funerary architecture in a project designed to outlast an individual life.",
      image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Giza_Pyramids_Panorama.jpg",
      imageAlt: "Archaeological photograph of the Giza pyramid complex in golden light",
      imageLabel: "Archaeological photograph",
      claimIds: ["giza-khufu-tomb", "giza-cardinal-alignment", "giza-royal-complex"],
      reflection: "What deserves to be preserved beyond one lifetime?"
    },
    {
      id: "we-descend",
      title: "We Descend",
      siteId: "hal-saflieni",
      siteName: "Ħal Saflieni",
      locationLabel: "Malta · c. 4000–2500 BCE",
      eyebrow: "Threshold 05 · Death",
      voice: "Descend inward.",
      humanInsight: "Not every sacred centre reaches upward. Some lead below the surface, using darkness, enclosure and carved chambers to hold the dead and alter the attention of the living.",
      image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Hal_Saflieni_Hypogeum_%E2%80%93_Middle_Level_%E2%80%93_The_Central_Chamber.jpg",
      imageAlt: "Archaeological photograph of the Ħal Saflieni Hypogeum's carved underground chambers",
      imageLabel: "Archaeological photograph",
      claimIds: ["hal-saflieni-subterranean-cemetery"],
      reflection: "What can only be encountered when we stop fleeing depth and mortality?"
    },
    {
      id: "we-shape-a-world",
      title: "We Shape a Living World",
      siteId: "angkor",
      siteName: "Angkor",
      locationLabel: "Khmer Empire · 9th–15th centuries",
      eyebrow: "Threshold 06 · Civilisation",
      voice: "Let the cosmos flow.",
      humanInsight: "At Angkor, temples were embedded in cities, reservoirs, canals, routes, farms and living communities. The sacred was not outside practical life; it helped organise a world.",
      image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Angkor_Wat_with_its_reflection_(cropped).jpg",
      imageAlt: "Archaeological photograph of Angkor Wat reflected in water at sunrise",
      imageLabel: "Archaeological photograph",
      claimIds: ["angkor-hydraulic-cosmos"],
      reflection: "What would it mean for our infrastructure to express care, balance and belonging?"
    },
    {
      id: "we-walk",
      title: "We Walk the Teaching",
      siteId: "borobudur",
      siteName: "Borobudur",
      locationLabel: "Central Java · 8th–9th centuries",
      eyebrow: "Threshold 07 · Transformation",
      voice: "The path changes the traveller.",
      humanInsight: "Borobudur does not only depict a cosmology. Its terraces invite movement through it, turning ascent, circling, relief and changing form into a physical pedagogy.",
      image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Borobudur_Sunrise.jpg",
      imageAlt: "Archaeological photograph of Borobudur's stupas above a misty valley",
      imageLabel: "Archaeological photograph",
      claimIds: ["borobudur-walking-cosmology"],
      reflection: "Which truths can be understood only by practising and moving through them?"
    }
  ]
};
