import type { Claim } from "@/types/content";

export const claims = {
  "giza-khufu-tomb": {
    id: "giza-khufu-tomb",
    siteId: "giza",
    title: "A royal tomb built for Khufu",
    statement: "The Great Pyramid is attributed to King Khufu of Egypt’s Fourth Dynasty and was built as the central monument of his royal funerary complex.",
    status: "established",
    sourceIds: ["egypt-ministry-great-pyramid", "digital-giza-faq"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The monument joined royal burial, political authority and Egyptian ideas about enduring cosmic order.",
    doesNotProve: "It does not establish every ritual performed there or settle every detail of the king’s afterlife theology.",
    tags: ["identity", "kingship", "funerary"],
    diagramLabel: "Khufu’s royal funerary complex"
  },
  "giza-scale-materials": {
    id: "giza-scale-materials",
    siteId: "giza",
    title: "Scale, stone and chambers",
    statement: "The pyramid originally stood about 146.5 metres high, used local limestone for much of its mass, carried fine Tura limestone casing, and contains three principal chambers described by the Egyptian Ministry.",
    status: "established",
    sourceIds: ["egypt-ministry-great-pyramid"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Its impact came from both extraordinary scale and tightly controlled differences in material and internal space.",
    doesNotProve: "Large scale and precision do not by themselves demonstrate unknown technology or a single secret mathematical code.",
    tags: ["engineering", "materials", "interior"],
    diagramLabel: "146.5 m original height"
  },
  "giza-tura-transport": {
    id: "giza-tura-transport",
    siteId: "giza",
    title: "Fine limestone moved through a river network",
    statement: "Inspector Merer’s logbooks record crews transporting limestone from the Tura quarries by water to Akhet-Khufu, the Great Pyramid project.",
    status: "established",
    sourceIds: ["ifao-merer"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The pyramid was the endpoint of a coordinated logistics network linking quarry, boat crews, waterways, administration and the construction site.",
    doesNotProve: "The logbooks do not describe the complete method used to lift and position every block in the pyramid.",
    tags: ["construction", "transport", "water"],
    diagramLabel: "Tura → water transport → Akhet-Khufu"
  },
  "giza-worker-city": {
    id: "giza-worker-city",
    siteId: "giza",
    title: "A supported workforce lived beside the plateau",
    statement: "Excavation at Heit el-Ghurab revealed a large settlement with galleries, bakeries, livestock facilities, officials’ houses and royal administration connected with pyramid-era work at Giza.",
    status: "established",
    sourceIds: ["aera-city"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Monumental building depended on food, housing, craft organisation, management and a society capable of sustaining specialised labour.",
    doesNotProve: "The settlement does not provide an exact total workforce figure or a complete day-by-day account of Great Pyramid construction.",
    tags: ["labour", "city", "logistics"],
    diagramLabel: "Workers’ settlement and supply system"
  },
  "giza-construction-method-open": {
    id: "giza-construction-method-open",
    siteId: "giza",
    title: "No complete construction sequence is established",
    statement: "Evidence documents quarrying, water transport, workers and parts of the building system, but no surviving source provides a complete end-to-end method for raising the Great Pyramid.",
    status: "open-mystery",
    sourceIds: ["egypt-ministry-great-pyramid", "ifao-merer", "aera-city"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The strongest explanations are likely combinations of known tools, ramps, hauling, levering, surveying and large-scale organisation rather than one spectacular trick.",
    doesNotProve: "An incomplete record is not positive evidence for aliens, levitation, lost industrial machinery or any particular untested mechanism.",
    tags: ["construction", "mystery", "methods"],
    diagramLabel: "Raising sequence: unresolved"
  },
  "giza-ahramat-branch": {
    id: "giza-ahramat-branch",
    siteId: "giza",
    title: "The pyramid landscape was once more watery",
    statement: "Geophysical and sediment research identifies an extinct Nile branch running beside many pyramid fields; numerous causeways terminate near it at valley temples that may have functioned as river harbors.",
    status: "probable",
    sourceIds: ["nature-ahramat", "digital-giza-faq"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The pyramids were not isolated desert objects: their original setting joined plateau, floodplain, water transport, harbor architecture and ceremonial approach.",
    doesNotProve: "The reconstructed branch does not mean the plateau itself was submerged or that water directly lifted blocks up the pyramid.",
    tags: ["landscape", "water", "transport"],
    diagramLabel: "Extinct Ahramat Nile branch"
  },
  "giza-royal-complex": {
    id: "giza-royal-complex",
    siteId: "giza",
    title: "The pyramid belonged to a connected ritual complex",
    statement: "Khufu’s pyramid complex included a mortuary temple beside the pyramid, a causeway extending east to a valley temple, subsidiary pyramids and associated boat pits.",
    status: "established",
    sourceIds: ["digital-giza-faq", "digital-giza-causeway", "digital-giza-boats"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Approach, movement, water, subsidiary monuments and ritual architecture mattered alongside the pyramid’s towering mass.",
    doesNotProve: "The surviving plan does not preserve every ceremony, sound, decoration or participant’s experience.",
    tags: ["complex", "ritual", "procession"],
    diagramLabel: "Valley temple → causeway → mortuary temple → pyramid"
  },
  "giza-complex-route": {
    id: "giza-complex-route",
    siteId: "giza",
    title: "Two temples were joined by a causeway",
    statement: "Khufu’s mortuary temple stood beside the pyramid, while a causeway extended eastward toward the valley temple at the riverward edge of the complex.",
    status: "established",
    sourceIds: ["digital-giza-faq", "digital-giza-causeway"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The complex organised ceremonial movement from low water-edge architecture toward the elevated pyramid plateau.",
    doesNotProve: "The surviving route does not preserve the complete sequence, wording or sensory detail of ancient ceremonies.",
    tags: ["causeway", "temples", "procession"],
    diagramLabel: "Valley temple → causeway → mortuary temple"
  },
  "giza-subsidiary-pyramids": {
    id: "giza-subsidiary-pyramids",
    siteId: "giza",
    title: "Subsidiary pyramids stood east of Khufu’s pyramid",
    statement: "Three queen’s pyramids are documented in a north–south line east of Khufu’s pyramid, alongside other subsidiary structures in the royal complex.",
    status: "established",
    sourceIds: ["digital-giza-queen-pyramid"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The monumental landscape distributed royal memory and ritual roles across several structures rather than one isolated mass.",
    doesNotProve: "The modern label ‘queen’s pyramid’ does not settle the identity or complete use history of every subsidiary structure.",
    tags: ["subsidiary", "royal-complex", "pyramids"],
    diagramLabel: "Three subsidiary pyramids east of Khufu"
  },
  "giza-boat-pits": {
    id: "giza-boat-pits",
    siteId: "giza",
    title: "Five boat pits are documented around the complex",
    statement: "Digital Giza catalogues five boat pits associated with Khufu’s pyramid complex, positioned along its southern and eastern sides.",
    status: "established",
    sourceIds: ["digital-giza-boats"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Boats and boat-shaped installations linked royal burial architecture with movement, transport and Egyptian ritual imagery.",
    doesNotProve: "The pits alone do not establish one identical function for every boat or pit across the complex.",
    tags: ["boats", "ritual", "complex"],
    diagramLabel: "Five documented boat pits"
  },
  "giza-cardinal-alignment": {
    id: "giza-cardinal-alignment",
    siteId: "giza",
    title: "The pyramid was aligned closely to the cardinal directions",
    statement: "The sides of the Great Pyramid are aligned closely to true north, south, east and west, with deviations small enough to require deliberate surveying.",
    status: "established",
    sourceIds: ["nature-alignment"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Orientation made the monument participate in a stable spatial order rather than merely occupy the plateau.",
    doesNotProve: "Precision does not identify the exact surveying procedure or demonstrate modern instruments.",
    tags: ["alignment", "surveying", "cardinal"],
    diagramLabel: "Near-cardinal orientation"
  },
  "giza-alignment-method": {
    id: "giza-alignment-method",
    siteId: "giza",
    title: "A stellar method is plausible but not settled",
    statement: "One published model proposes that Egyptian surveyors established north by observing the simultaneous transit of two circumpolar stars, but the exact ancient procedure remains debated.",
    status: "contested",
    sourceIds: ["nature-alignment"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The method shows how careful naked-eye observation could theoretically produce the required accuracy.",
    doesNotProve: "A model that fits the measurements is not the same as a settled eyewitness account.",
    tags: ["alignment", "stars", "method"],
    diagramLabel: "Proposed circumpolar-star method"
  },
  "giza-known-interior": {
    id: "giza-known-interior",
    siteId: "giza",
    title: "The known interior forms a vertical sequence",
    statement: "The known passages connect a subterranean chamber cut below the pyramid with elevated masonry chambers, including the so-called Queen’s Chamber, Grand Gallery and King’s Chamber.",
    status: "established",
    sourceIds: ["egypt-ministry-great-pyramid", "nature-north-corridor"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Moving through the monument is a bodily journey of compression, ascent, release and enclosure, even when the precise ritual meaning of each transition is uncertain.",
    doesNotProve: "The modern chamber names are not proof of their original names or exact functions.",
    tags: ["interior", "journey", "space"],
    diagramLabel: "Below ground → ascending passages → upper chambers"
  },
  "giza-big-void": {
    id: "giza-big-void",
    siteId: "giza",
    title: "A large void exists above the Grand Gallery",
    statement: "Muon imaging detected a void with a minimum length of 30 metres above the Grand Gallery, confirmed through three detection technologies and independent analyses.",
    status: "established",
    sourceIds: ["nature-big-void"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Non-destructive physics can reveal large structural features while leaving their architectural role unresolved.",
    doesNotProve: "The detection does not show that the void contains treasure, records, machinery, a royal body or an accessible chamber.",
    tags: ["interior", "muons", "discovery"],
    diagramLabel: "Big Void: ≥30 m; purpose unknown"
  },
  "giza-north-face-corridor": {
    id: "giza-north-face-corridor",
    siteId: "giza",
    title: "A corridor lies behind the north-face chevrons",
    statement: "Muon measurements characterised a corridor-shaped structure behind the north-face chevrons as roughly 9 metres long with a transverse section of about 2 by 2 metres.",
    status: "established",
    sourceIds: ["nature-north-corridor"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The corridor may help researchers understand how the chevron structure manages space or load, but interpretation requires more evidence.",
    doesNotProve: "Its existence does not establish a hidden entrance, secret archive or connection to the Big Void.",
    tags: ["interior", "muons", "corridor"],
    diagramLabel: "North Face Corridor: ~9 m"
  },
  "giza-void-purpose": {
    id: "giza-void-purpose",
    siteId: "giza",
    title: "The functions of the detected spaces remain unresolved",
    statement: "The research teams that detected the Big Void and North Face Corridor did not establish their intended ancient functions.",
    status: "open-mystery",
    sourceIds: ["nature-big-void", "nature-north-corridor"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Open questions should remain open until geometry, access, construction context and comparative evidence narrow the possibilities.",
    doesNotProve: "Scientific uncertainty is not a blank cheque for whichever explanation is most dramatic.",
    tags: ["mystery", "interior", "method"],
    diagramLabel: "Detected ≠ explained"
  },
  "gobekli-monumental-gathering": {
    id: "gobekli-monumental-gathering",
    siteId: "gobekli-tepe",
    title: "Early communities built monumental gathering places",
    statement: "At Göbekli Tepe, Pre-Pottery Neolithic communities erected monumental communal or special-purpose buildings between roughly 9600 and 8200 BCE using distinctive T-shaped limestone pillars.",
    status: "established",
    sourceIds: ["unesco-gobekli", "dai-gobekli-faq"],
    reviewedOn: "2026-07-29",
    editorialState: "published",
    version: 2,
    owner: "atlas-editorial",
    interpretation: "Large-scale symbolic gathering was not merely a late luxury of cities; early communities made shared worlds visible in architecture.",
    doesNotProve: "The site does not prove that one religion created civilisation, that every monumental building was a temple, or that all structures served one identical function.",
    tags: ["gathering", "monumentality", "community"],
    diagramLabel: "Monumental gathering before cities"
  },
  "gobekli-chronology": {
    id: "gobekli-chronology",
    siteId: "gobekli-tepe",
    title: "The site changed across many centuries",
    statement: "Göbekli Tepe preserves Pre-Pottery Neolithic building activity across the tenth and ninth millennia BCE, including earlier monumental round-oval buildings and later generally smaller rectangular architecture.",
    status: "established",
    sourceIds: ["unesco-gobekli", "dai-gobekli-faq", "archaeology-gobekli-stratigraphy"],
    reviewedOn: "2026-07-29",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The site is a changing architectural history rather than one frozen moment or single building event.",
    doesNotProve: "The broad architectural sequence does not establish a simple linear transition from ritual to domestic life or from mobile to fully settled communities.",
    tags: ["chronology", "architecture", "change"],
    diagramLabel: "Round-oval → rectangular · with overlap and revision"
  },
  "gobekli-regional-network": {
    id: "gobekli-regional-network",
    siteId: "gobekli-tepe",
    title: "Göbekli Tepe belonged to a wider regional network",
    statement: "Related T-shaped pillars, architectural forms and imagery occur at contemporaneous sites across Upper Mesopotamia, placing Göbekli Tepe within a broader early-Neolithic cultural landscape.",
    status: "established",
    sourceIds: ["unesco-gobekli", "dai-gobekli-pillars", "dai-tas-tepeler"],
    reviewedOn: "2026-07-29",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Monumental building participated in relationships between communities rather than emerging as an isolated miracle on one hill.",
    doesNotProve: "Shared forms do not establish one state, central authority, ethnic identity or single regional religion.",
    tags: ["region", "network", "tas-tepeler"],
    diagramLabel: "A constellation of early-Neolithic hills"
  },
  "gobekli-apparent-domestic": {
    id: "gobekli-apparent-domestic",
    siteId: "gobekli-tepe",
    title: "Daily life was present beside monumental gathering",
    statement: "Excavation has identified non-monumental structures that appear domestic, alongside evidence associated with habitation and daily activity such as food remains, fire installations, water collection and dense building remains.",
    status: "probable",
    sourceIds: ["unesco-gobekli", "dai-gobekli-faq", "plos-gobekli-cereals"],
    reviewedOn: "2026-07-29",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Göbekli Tepe should be understood as a lived place where domestic, communal, practical and symbolic activity could overlap.",
    doesNotProve: "The evidence does not mean every building was a house or settle how permanent occupation was during every phase.",
    tags: ["habitation", "domestic", "daily-life"],
    diagramLabel: "Gathering place and lived place"
  },
  "gobekli-anthropomorphic-pillars": {
    id: "gobekli-anthropomorphic-pillars",
    siteId: "gobekli-tepe",
    title: "Some T-pillars carry human-like bodies",
    statement: "Several T-shaped pillars bear carved arms, hands, belts and loincloths, supporting their description as abstract anthropomorphic forms while they also functioned as architectural elements.",
    status: "established",
    sourceIds: ["unesco-gobekli", "dai-gobekli-faq", "dai-gobekli-pillars"],
    reviewedOn: "2026-07-29",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Architecture and embodied presence meet: the pillars can hold a building while also evoking beings gathered within it.",
    doesNotProve: "Anthropomorphic features do not identify the figures as gods, ancestors, priests, rulers or named mythological beings.",
    tags: ["pillars", "body", "anthropomorphic"],
    diagramLabel: "Head-like form · arms · hands · belt"
  },
  "gobekli-animal-imagery": {
    id: "gobekli-animal-imagery",
    siteId: "gobekli-tepe",
    title: "Wild animals structure the visual world",
    statement: "Pillars and small finds at Göbekli Tepe carry reliefs of wild animals and abstract signs, with motif frequencies and combinations differing between excavated buildings.",
    status: "established",
    sourceIds: ["unesco-gobekli", "dai-gobekli-faq", "cambridge-gobekli-relationality"],
    reviewedOn: "2026-07-29",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The imagery suggests that human identity was articulated through relationships with other beings, dangers, memories or stories whose exact language is lost.",
    doesNotProve: "Recognisable species and image placement do not establish a zodiac, comet record, clan system or one recoverable myth.",
    tags: ["animals", "imagery", "relations"],
    diagramLabel: "Fox · boar · birds · snakes · signs"
  },
  "gobekli-local-quarries": {
    id: "gobekli-local-quarries",
    siteId: "gobekli-tepe",
    title: "The pillars came from the limestone plateau",
    statement: "Quarry areas, extraction traces and unfinished workpieces on the surrounding limestone plateau document local production of the monumental pillars.",
    status: "established",
    sourceIds: ["unesco-gobekli", "dai-gobekli-monoliths"],
    reviewedOn: "2026-07-29",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The monumental forms began within the hill itself, turning local stone into a coordinated architecture of gathering.",
    doesNotProve: "Quarry evidence does not preserve the exact workforce, transport rig, authority structure or raising sequence for every pillar.",
    tags: ["quarry", "limestone", "labour"],
    diagramLabel: "Plateau quarry → unfinished pillar → building"
  },
  "gobekli-cereal-processing": {
    id: "gobekli-cereal-processing",
    siteId: "gobekli-tepe",
    title: "Cereal processing occurred at substantial scale",
    statement: "Analysis of more than 7,000 grinding tools from Göbekli Tepe identified widespread use-wear connected with cereal processing across buildings, open spaces and deposits.",
    status: "established",
    sourceIds: ["plos-gobekli-cereals"],
    reviewedOn: "2026-07-29",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Monumental gathering depended on repeated work of provisioning, processing and maintaining life—not symbolism alone.",
    doesNotProve: "Grinding tools do not by themselves prove domesticated crops, a single central feast, universal beer production or that feasting caused monumentality.",
    tags: ["food", "cereals", "provisioning"],
    diagramLabel: "7,000+ grinding tools analysed"
  },
  "gobekli-building-biographies": {
    id: "gobekli-building-biographies",
    siteId: "gobekli-tepe",
    title: "Buildings were altered, filled and sealed through complex histories",
    statement: "Architectural and depositional research indicates that Göbekli Tepe’s buildings were modified and filled through combinations of human deposition, later construction, collapse and sediment movement rather than one demonstrable site-wide event.",
    status: "probable",
    sourceIds: ["plos-gobekli-cereals", "archaeology-gobekli-stratigraphy"],
    reviewedOn: "2026-07-29",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "A building’s ending could be a long biography of repair, reuse, deposition and landscape process rather than one ceremonial burial.",
    doesNotProve: "The mixed evidence does not rule out intentional deposits in particular contexts, nor support claiming that the whole site was deliberately buried all at once.",
    tags: ["infill", "stratigraphy", "building-biography"],
    diagramLabel: "Repair · deposition · collapse · slope movement"
  },
  "gobekli-social-organisation-open": {
    id: "gobekli-social-organisation-open",
    siteId: "gobekli-tepe",
    title: "Coordination is visible; the political structure is not",
    statement: "Quarrying, carving, provisioning and maintaining monumental buildings required coordinated labour, planning and specialised knowledge, while the enduring form of leadership or hierarchy remains unresolved.",
    status: "open-mystery",
    sourceIds: ["dai-gobekli-monoliths", "plos-gobekli-cereals", "cambridge-gobekli-geometry", "unesco-gobekli"],
    reviewedOn: "2026-07-29",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The site makes collective capacity visible while leaving open whether cooperation relied on seasonal alliances, households, specialists, temporary leaders or stronger hierarchy.",
    doesNotProve: "Coordination does not automatically prove kings, coercive labour, permanent priests or a fully stratified state society.",
    tags: ["organisation", "leadership", "cooperation"],
    diagramLabel: "Coordination established · authority unresolved"
  },
  "gobekli-meaning-open": {
    id: "gobekli-meaning-open",
    siteId: "gobekli-tepe",
    title: "No single function or belief is established",
    statement: "Architecture, imagery, food activity, deposition and repeated gathering support social and ritual interpretations, but no text or decisive evidence establishes one purpose for every building or the builders’ own explanation.",
    status: "open-mystery",
    sourceIds: ["unesco-gobekli", "dai-gobekli-faq", "antiquity-gobekli-feasting", "cambridge-gobekli-relationality"],
    reviewedOn: "2026-07-29",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The honest centre of the portal is plurality: dwelling, work, memory, gathering and ritual may have overlapped and changed across centuries.",
    doesNotProve: "Calling the buildings temples, sanctuaries, houses, clan buildings or funerary spaces does not become fact merely because one label is compelling.",
    tags: ["meaning", "ritual", "open-question"],
    diagramLabel: "Observed activity ≠ recovered belief"
  },
  "gobekli-conservation-priority": {
    id: "gobekli-conservation-priority",
    siteId: "gobekli-tepe",
    title: "Preservation now limits further excavation",
    statement: "UNESCO’s 2025 conservation decision urged limiting further archaeological excavation and intervention to urgent stabilisation and preventive maintenance pending comprehensive conservation and revised management plans.",
    status: "established",
    sourceIds: ["unesco-gobekli-conservation-2025", "dai-gobekli-faq"],
    reviewedOn: "2026-07-29",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Responsible knowledge sometimes means leaving archaeology undisturbed until preservation can be secured.",
    doesNotProve: "Limits on excavation do not imply a cover-up or that research has stopped; conservation, survey, documentation and analysis remain forms of discovery.",
    tags: ["conservation", "stewardship", "excavation"],
    diagramLabel: "Excavate less · preserve more context"
  },
  "stonehenge-ceremonial-landscape": {
    id: "stonehenge-ceremonial-landscape",
    siteId: "stonehenge",
    title: "A monument inside a long-used ceremonial landscape",
    statement: "Stonehenge belongs to a wider landscape of Neolithic and Bronze Age ceremonial and funerary monuments shaped through roughly two millennia of building and use.",
    status: "established",
    sourceIds: ["unesco-stonehenge"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The circle can be understood less as an isolated object than as a place where time, memory, movement and community met.",
    doesNotProve: "Its astronomical relationships do not establish a modern observatory, a single-purpose calendar or one uncontested ritual programme.",
    tags: ["time", "landscape", "ceremony"],
    diagramLabel: "Time is sacred"
  },
  "newgrange-solstice-light": {
    id: "newgrange-solstice-light",
    siteId: "newgrange",
    title: "Midwinter sunrise enters the chamber",
    statement: "Around the winter solstice, direct sunrise light can pass through Newgrange's roof box, travel along the passage and illuminate the inner chamber for up to about seventeen minutes.",
    status: "established",
    sourceIds: ["opw-newgrange-solstice", "unesco-bru-na-boinne"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Architecture turns the return of light into an embodied event inside a funerary landscape: darkness is not simply ended, but crossed.",
    doesNotProve: "The illumination does not preserve the exact words, beliefs or emotional responses of the people who built and used the monument.",
    tags: ["light", "solstice", "renewal"],
    diagramLabel: "Light returns through stone"
  },
  "hal-saflieni-subterranean-cemetery": {
    id: "hal-saflieni-subterranean-cemetery",
    siteId: "hal-saflieni",
    title: "A three-level world cut beneath the ground",
    statement: "The Ħal Saflieni Hypogeum is a subterranean cemetery cut into limestone on three levels and used during Maltese prehistory from around 4000 to 2500 BCE.",
    status: "established",
    sourceIds: ["unesco-hal-saflieni"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Sacred architecture can descend rather than rise, using enclosure, darkness and carved imitation of built space to hold the dead and reshape the living visitor's attention.",
    doesNotProve: "The surviving chambers do not establish that every acoustic effect was deliberately engineered or that the complex served a single initiation ritual.",
    tags: ["descent", "death", "subterranean"],
    diagramLabel: "Descend inward"
  },
  "angkor-hydraulic-cosmos": {
    id: "angkor-hydraulic-cosmos",
    siteId: "angkor",
    title: "Temples, cities and water formed one inhabited system",
    statement: "Angkor extended across hundreds of square kilometres and combined temples, successive urban plans, reservoirs, canals, dykes and routes at the centre of the Khmer Kingdom.",
    status: "established",
    sourceIds: ["unesco-angkor"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "At Angkor, sacred order was not confined to a sanctuary: water, settlement, royal power, agriculture and symbolic architecture participated in a living world.",
    doesNotProve: "The scale of the hydraulic landscape does not mean every canal or reservoir had the same ritual meaning or that symbolic interpretation replaces practical engineering.",
    tags: ["water", "city", "cosmos"],
    diagramLabel: "Let the cosmos flow"
  },
  "borobudur-walking-cosmology": {
    id: "borobudur-walking-cosmology",
    siteId: "borobudur",
    title: "A monument organised as a path through Buddhist cosmology",
    statement: "Borobudur's square terraces, circular platforms, reliefs and stupas form a stepped monument whose vertical organisation corresponds to realms described in Buddhist cosmology.",
    status: "established",
    sourceIds: ["unesco-borobudur"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The teaching becomes spatial: a visitor moves, circles, ascends and gradually encounters a different architectural language.",
    doesNotProve: "The monument does not reduce Buddhist practice to one universal staircase or establish that every historical visitor experienced the route identically.",
    tags: ["pilgrimage", "cosmology", "ascent"],
    diagramLabel: "Walk the teaching"
  }
} satisfies Record<string, Claim>;

export type ClaimId = keyof typeof claims;
