import type { Claim } from "@/types/content";

export const claims = {
  "giza-khufu-tomb": {
    id: "giza-khufu-tomb",
    siteId: "giza",
    title: "A royal tomb built for Khufu",
    statement: "The Great Pyramid is attributed to King Khufu of Egypt’s Fourth Dynasty and was built as the central monument of his royal funerary complex.",
    status: "established",
    sourceIds: ["egypt-ministry-great-pyramid", "digital-giza-faq"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The monument joined royal burial, political authority and Egyptian ideas about enduring cosmic order.",
    doesNotProve: "It does not establish every ritual performed there or settle every detail of the king’s afterlife theology.",
    tags: ["identity", "kingship", "funerary"],
    diagramLabel: "Khufu’s royal funerary complex"
  },
  "giza-scale-materials": {
    id: "giza-scale-materials",
    siteId: "giza",
    title: "Scale, stone and chambers",
    statement: "The pyramid originally stood about 146.5 metres high, used local limestone for much of its mass, carried fine Tura limestone casing, and contains three principal chambers described by the Egyptian Ministry.",
    status: "established",
    sourceIds: ["egypt-ministry-great-pyramid"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Its impact came from both extraordinary scale and tightly controlled differences in material and internal space.",
    doesNotProve: "Large scale and precision do not by themselves demonstrate unknown technology or a single secret mathematical code.",
    tags: ["engineering", "materials", "interior"],
    diagramLabel: "146.5 m original height"
  },
  "giza-tura-transport": {
    id: "giza-tura-transport",
    siteId: "giza",
    title: "Fine limestone moved through a river network",
    statement: "Inspector Merer’s logbooks record crews transporting limestone from the Tura quarries by water to Akhet-Khufu, the Great Pyramid project.",
    status: "established",
    sourceIds: ["ifao-merer"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The pyramid was the endpoint of a coordinated logistics network linking quarry, boat crews, waterways, administration and the construction site.",
    doesNotProve: "The logbooks do not describe the complete method used to lift and position every block in the pyramid.",
    tags: ["construction", "transport", "water"],
    diagramLabel: "Tura → water transport → Akhet-Khufu"
  },
  "giza-worker-city": {
    id: "giza-worker-city",
    siteId: "giza",
    title: "A supported workforce lived beside the plateau",
    statement: "Excavation at Heit el-Ghurab revealed a large settlement with galleries, bakeries, livestock facilities, officials’ houses and royal administration connected with pyramid-era work at Giza.",
    status: "established",
    sourceIds: ["aera-city"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Monumental building depended on food, housing, craft organisation, management and a society capable of sustaining specialised labour.",
    doesNotProve: "The settlement does not provide an exact total workforce figure or a complete day-by-day account of Great Pyramid construction.",
    tags: ["labour", "city", "logistics"],
    diagramLabel: "Workers’ settlement and supply system"
  },
  "giza-construction-method-open": {
    id: "giza-construction-method-open",
    siteId: "giza",
    title: "No complete construction sequence is established",
    statement: "Evidence documents quarrying, water transport, workers and parts of the building system, but no surviving source provides a complete end-to-end method for raising the Great Pyramid.",
    status: "open-mystery",
    sourceIds: ["egypt-ministry-great-pyramid", "ifao-merer", "aera-city"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The strongest explanations are likely combinations of known tools, ramps, hauling, levering, surveying and large-scale organisation rather than one spectacular trick.",
    doesNotProve: "An incomplete record is not positive evidence for aliens, levitation, lost industrial machinery or any particular untested mechanism.",
    tags: ["construction", "mystery", "methods"],
    diagramLabel: "Raising sequence: unresolved"
  },
  "giza-ahramat-branch": {
    id: "giza-ahramat-branch",
    siteId: "giza",
    title: "The pyramid landscape was once more watery",
    statement: "Geophysical and sediment research identifies an extinct Nile branch running beside many pyramid fields; numerous causeways terminate near it at valley temples that may have functioned as river harbors.",
    status: "probable",
    sourceIds: ["nature-ahramat", "digital-giza-faq"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The pyramids were not isolated desert objects: their original setting joined plateau, floodplain, water transport, harbor architecture and ceremonial approach.",
    doesNotProve: "The reconstructed branch does not mean the plateau itself was submerged or that water directly lifted blocks up the pyramid.",
    tags: ["landscape", "water", "transport"],
    diagramLabel: "Extinct Ahramat Nile branch"
  },
  "giza-royal-complex": {
    id: "giza-royal-complex",
    siteId: "giza",
    title: "The pyramid belonged to a connected ritual complex",
    statement: "Khufu’s pyramid complex included a mortuary temple beside the pyramid, a causeway extending east to a valley temple, subsidiary pyramids and associated boat pits.",
    status: "established",
    sourceIds: ["digital-giza-faq", "digital-giza-causeway", "digital-giza-boats"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Approach, movement, water, subsidiary monuments and ritual architecture mattered alongside the pyramid’s towering mass.",
    doesNotProve: "The surviving plan does not preserve every ceremony, sound, decoration or participant’s experience.",
    tags: ["complex", "ritual", "procession"],
    diagramLabel: "Valley temple → causeway → mortuary temple → pyramid"
  },
  "giza-complex-route": {
    id: "giza-complex-route",
    siteId: "giza",
    title: "Two temples were joined by a causeway",
    statement: "Khufu’s mortuary temple stood beside the pyramid, while a causeway extended eastward toward the valley temple at the riverward edge of the complex.",
    status: "established",
    sourceIds: ["digital-giza-faq", "digital-giza-causeway"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The complex organised ceremonial movement from low water-edge architecture toward the elevated pyramid plateau.",
    doesNotProve: "The surviving route does not preserve the complete sequence, wording or sensory detail of ancient ceremonies.",
    tags: ["causeway", "temples", "procession"],
    diagramLabel: "Valley temple → causeway → mortuary temple"
  },
  "giza-subsidiary-pyramids": {
    id: "giza-subsidiary-pyramids",
    siteId: "giza",
    title: "Subsidiary pyramids stood east of Khufu’s pyramid",
    statement: "Three queen’s pyramids are documented in a north–south line east of Khufu’s pyramid, alongside other subsidiary structures in the royal complex.",
    status: "established",
    sourceIds: ["digital-giza-queen-pyramid"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The monumental landscape distributed royal memory and ritual roles across several structures rather than one isolated mass.",
    doesNotProve: "The modern label ‘queen’s pyramid’ does not settle the identity or complete use history of every subsidiary structure.",
    tags: ["subsidiary", "royal-complex", "pyramids"],
    diagramLabel: "Three subsidiary pyramids east of Khufu"
  },
  "giza-boat-pits": {
    id: "giza-boat-pits",
    siteId: "giza",
    title: "Five boat pits are documented around the complex",
    statement: "Digital Giza catalogues five boat pits associated with Khufu’s pyramid complex, positioned along its southern and eastern sides.",
    status: "established",
    sourceIds: ["digital-giza-boats"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Boats and boat-shaped installations linked royal burial architecture with movement, transport and Egyptian ritual imagery.",
    doesNotProve: "The pits alone do not establish one identical function for every boat or pit across the complex.",
    tags: ["boats", "ritual", "complex"],
    diagramLabel: "Five documented boat pits"
  },
  "giza-cardinal-alignment": {
    id: "giza-cardinal-alignment",
    siteId: "giza",
    title: "The pyramid was aligned closely to the cardinal directions",
    statement: "The sides of the Great Pyramid are aligned closely to true north, south, east and west, with deviations small enough to require deliberate surveying.",
    status: "established",
    sourceIds: ["nature-alignment"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Orientation made the monument participate in a stable spatial order rather than merely occupy the plateau.",
    doesNotProve: "Precision does not identify the exact surveying procedure or demonstrate modern instruments.",
    tags: ["alignment", "surveying", "cardinal"],
    diagramLabel: "Near-cardinal orientation"
  },
  "giza-alignment-method": {
    id: "giza-alignment-method",
    siteId: "giza",
    title: "A stellar method is plausible but not settled",
    statement: "One published model proposes that Egyptian surveyors established north by observing the simultaneous transit of two circumpolar stars, but the exact ancient procedure remains debated.",
    status: "contested",
    sourceIds: ["nature-alignment"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The method shows how careful naked-eye observation could theoretically produce the required accuracy.",
    doesNotProve: "A model that fits the measurements is not the same as a settled eyewitness account.",
    tags: ["alignment", "stars", "method"],
    diagramLabel: "Proposed circumpolar-star method"
  },
  "giza-known-interior": {
    id: "giza-known-interior",
    siteId: "giza",
    title: "The known interior forms a vertical sequence",
    statement: "The known passages connect a subterranean chamber cut below the pyramid with elevated masonry chambers, including the so-called Queen’s Chamber, Grand Gallery and King’s Chamber.",
    status: "established",
    sourceIds: ["egypt-ministry-great-pyramid", "nature-north-corridor"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Moving through the monument is a bodily journey of compression, ascent, release and enclosure, even when the precise ritual meaning of each transition is uncertain.",
    doesNotProve: "The modern chamber names are not proof of their original names or exact functions.",
    tags: ["interior", "journey", "space"],
    diagramLabel: "Below ground → ascending passages → upper chambers"
  },
  "giza-big-void": {
    id: "giza-big-void",
    siteId: "giza",
    title: "A large void exists above the Grand Gallery",
    statement: "Muon imaging detected a void with a minimum length of 30 metres above the Grand Gallery, confirmed through three detection technologies and independent analyses.",
    status: "established",
    sourceIds: ["nature-big-void"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Non-destructive physics can reveal large structural features while leaving their architectural role unresolved.",
    doesNotProve: "The detection does not show that the void contains treasure, records, machinery, a royal body or an accessible chamber.",
    tags: ["interior", "muons", "discovery"],
    diagramLabel: "Big Void: ≥30 m; purpose unknown"
  },
  "giza-north-face-corridor": {
    id: "giza-north-face-corridor",
    siteId: "giza",
    title: "A corridor lies behind the north-face chevrons",
    statement: "Muon measurements characterised a corridor-shaped structure behind the north-face chevrons as roughly 9 metres long with a transverse section of about 2 by 2 metres.",
    status: "established",
    sourceIds: ["nature-north-corridor"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The corridor may help researchers understand how the chevron structure manages space or load, but interpretation requires more evidence.",
    doesNotProve: "Its existence does not establish a hidden entrance, secret archive or connection to the Big Void.",
    tags: ["interior", "muons", "corridor"],
    diagramLabel: "North Face Corridor: ~9 m"
  },
  "giza-void-purpose": {
    id: "giza-void-purpose",
    siteId: "giza",
    title: "The functions of the detected spaces remain unresolved",
    statement: "The research teams that detected the Big Void and North Face Corridor did not establish their intended ancient functions.",
    status: "open-mystery",
    sourceIds: ["nature-big-void", "nature-north-corridor"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Open questions should remain open until geometry, access, construction context and comparative evidence narrow the possibilities.",
    doesNotProve: "Scientific uncertainty is not a blank cheque for whichever explanation is most dramatic.",
    tags: ["mystery", "interior", "method"],
    diagramLabel: "Detected ≠ explained"
  },
  "gobekli-monumental-gathering": {
    id: "gobekli-monumental-gathering",
    siteId: "gobekli-tepe",
    title: "Hunter-gatherers built monumental communal enclosures",
    statement: "At Göbekli Tepe, groups living during the Pre-Pottery Neolithic erected monumental structures between roughly 9600 and 8200 BCE, using distinctive carved T-shaped limestone pillars.",
    status: "established",
    sourceIds: ["unesco-gobekli"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Large-scale symbolic gathering was not merely a late luxury of urban civilisation; it helped early communities make social worlds visible.",
    doesNotProve: "The site does not prove that one religion created civilisation, that agriculture had no role in regional change, or that every enclosure had one identical function.",
    tags: ["gathering", "ritual", "monumentality"],
    diagramLabel: "Meaning gathers us"
  },
  "stonehenge-ceremonial-landscape": {
    id: "stonehenge-ceremonial-landscape",
    siteId: "stonehenge",
    title: "A monument inside a long-used ceremonial landscape",
    statement: "Stonehenge belongs to a wider landscape of Neolithic and Bronze Age ceremonial and funerary monuments shaped through roughly two millennia of building and use.",
    status: "established",
    sourceIds: ["unesco-stonehenge"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The circle can be understood less as an isolated object than as a place where time, memory, movement and community met.",
    doesNotProve: "Its astronomical relationships do not establish a modern observatory, a single-purpose calendar or one uncontested ritual programme.",
    tags: ["time", "landscape", "ceremony"],
    diagramLabel: "Time is sacred"
  },
  "newgrange-solstice-light": {
    id: "newgrange-solstice-light",
    siteId: "newgrange",
    title: "Midwinter sunrise enters the chamber",
    statement: "Around the winter solstice, direct sunrise light can pass through Newgrange's roof box, travel along the passage and illuminate the inner chamber for up to about seventeen minutes.",
    status: "established",
    sourceIds: ["opw-newgrange-solstice", "unesco-bru-na-boinne"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Architecture turns the return of light into an embodied event inside a funerary landscape: darkness is not simply ended, but crossed.",
    doesNotProve: "The illumination does not preserve the exact words, beliefs or emotional responses of the people who built and used the monument.",
    tags: ["light", "solstice", "renewal"],
    diagramLabel: "Light returns through stone"
  },
  "hal-saflieni-subterranean-cemetery": {
    id: "hal-saflieni-subterranean-cemetery",
    siteId: "hal-saflieni",
    title: "A three-level world cut beneath the ground",
    statement: "The Ħal Saflieni Hypogeum is a subterranean cemetery cut into limestone on three levels and used during Maltese prehistory from around 4000 to 2500 BCE.",
    status: "established",
    sourceIds: ["unesco-hal-saflieni"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "Sacred architecture can descend rather than rise, using enclosure, darkness and carved imitation of built space to hold the dead and reshape the living visitor's attention.",
    doesNotProve: "The surviving chambers do not establish that every acoustic effect was deliberately engineered or that the complex served a single initiation ritual.",
    tags: ["descent", "death", "subterranean"],
    diagramLabel: "Descend inward"
  },
  "angkor-hydraulic-cosmos": {
    id: "angkor-hydraulic-cosmos",
    siteId: "angkor",
    title: "Temples, cities and water formed one inhabited system",
    statement: "Angkor extended across hundreds of square kilometres and combined temples, successive urban plans, reservoirs, canals, dykes and routes at the centre of the Khmer Kingdom.",
    status: "established",
    sourceIds: ["unesco-angkor"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "At Angkor, sacred order was not confined to a sanctuary: water, settlement, royal power, agriculture and symbolic architecture participated in a living world.",
    doesNotProve: "The scale of the hydraulic landscape does not mean every canal or reservoir had the same ritual meaning or that symbolic interpretation replaces practical engineering.",
    tags: ["water", "city", "cosmos"],
    diagramLabel: "Let the cosmos flow"
  },
  "borobudur-walking-cosmology": {
    id: "borobudur-walking-cosmology",
    siteId: "borobudur",
    title: "A monument organised as a path through Buddhist cosmology",
    statement: "Borobudur's square terraces, circular platforms, reliefs and stupas form a stepped monument whose vertical organisation corresponds to realms described in Buddhist cosmology.",
    status: "established",
    sourceIds: ["unesco-borobudur"],
    reviewedOn: "2026-07-28",
    editorialState: "published",
    version: 1,
    owner: "atlas-editorial",
    interpretation: "The teaching becomes spatial: a visitor moves, circles, ascends and gradually encounters a different architectural language.",
    doesNotProve: "The monument does not reduce Buddhist practice to one universal staircase or establish that every historical visitor experienced the route identically.",
    tags: ["pilgrimage", "cosmology", "ascent"],
    diagramLabel: "Walk the teaching"
  }
} satisfies Record<string, Claim>;

export type ClaimId = keyof typeof claims;
